name: jalebi_shop_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  get: ^4.6.6
  http: ^0.13.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboardingImages/womanpizza.svg
    - assets/onb1.png
    - assets/onb2.png
    - assets/onb3.png
    - assets/shopping-bag.png
    - assets/pizza.png
    - assets/burgerphoto.png
    - assets/product_detail.png
    - assets/carttitem.png
    - assets/orderedfoof.png
    - assets/person.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sen-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sen-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen-ExtraBold.ttf
          weight: 800

