name: jalebi_shop_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  get: ^4.6.6
  http: ^0.13.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  razorpay_flutter: ^1.3.5
  sqflite: ^2.3.0
  path: ^1.9.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  visibility_detector: ^0.4.0
  synchronized: ^3.0.0
  fluttertoast: ^8.2.9
  image_picker: ^1.0.7
  dio: ^5.4.0
  http_parser: ^4.0.2
  mime: ^1.0.4
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.13.1
  google_mobile_ads: ^4.0.0
  firebase_core: ^2.30.0
  firebase_app_installations: ^0.2.4+2
  mobile_scanner: ^4.0.0




flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon.png"



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onb1.png
    - assets/onb2.png
    - assets/onb3.png
    - assets/shopping-bag.png
    - assets/person.png
    - assets/sucessconfti.png
    - assets/me.jpg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sen-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sen-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen-ExtraBold.ttf
          weight: 800

